# .github/workflows/agent-transformation-library-to-feature.yml
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: transformation-03-library-to-feature
#concurrency: library-to-feature
run-name: "library documents >> feature"

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Text to drive the feature creation (if "house choice", the repository will be assessed and an action chosen). e.g. "Support output to PDF."'
        required: false
        type: string
        default: 'house choice'
  #workflow_run:
  #  workflows:
  #    - agent-source-to-library
  #  types:
  #    - completed
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN:
  #      required: false
  #    CHATGPT_API_SECRET_KEY:
  #      required: true
  workflow_call:
    inputs:
      feature:
        description: 'Text to drive the feature creation (if "house choice", the repository will be assessed and an action chosen). e.g. "Support output to PDF."'
        required: false
        type: string
        default: 'house choice'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
      CHATGPT_API_SECRET_KEY:
        required: true
  schedule:
    - cron: '24 4 */7 * *' # schedule-1
    #- cron: '24 4 * * *' # schedule-2
    #- cron: '24 */2 * * *' # schedule-3
    #- cron: '24 7 * * *' # schedule-4

env:
  npmAuthOrganisation: ${{ vars.npmAuthOrganisation || '@xn-intenton-z2a' }}
  s3BucketUrl: ${{ vars.s3BucketUrl || 's3://agentic-lib-telemetry-bucket/events/' }}
  s3WebsiteBucketUrl: ${{ vars.s3WebsiteBucketUrl || 's3://agentic-lib-public-website-stats-bucket/' }}
  iamActionsRoleArn: ${{ vars.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}
  iamStatsBucketWriterRoleArn: ${{ vars.iamStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-deployment-role' }}
  iamPublicWebsiteStatsBucketWriterRoleArn: ${{ vars.iamPublicWebsiteStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-public-website-stats-bucket-writer-role' }}

jobs:

  agentic-lib:
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-agent-config.yml@6.4.7'
    with:
      configPath: ${{ vars.configPath || '.github/agents/agentic-lib.yml' }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # If the feature is "house choice", then the repository will be assessed an action chosen otherwise the supplied text will be used to generate a new feature.
  maintain-features:
    needs:
      - agentic-lib
    permissions:
      contents: write
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-completion-maintain-features.yml@6.4.7'
    with:
      promptFilepath: '.github/agents/agent-maintain-features.md'
      agentConfigContent: ${{ needs.agentic-lib.outputs.agentConfigContent }}
      feature: ${{ inputs.feature }}
      featuresPath: ${{ needs.agentic-lib.outputs.featuresPath }}
      featuresLimit: '${{ needs.agentic-lib.outputs.featuresLimit }}'
      allSourcePaths: ${{ needs.agentic-lib.outputs.allSourcePaths }}
      allTestsPaths: ${{ needs.agentic-lib.outputs.allTestsPaths }}
      documentationPath: ${{ needs.agentic-lib.outputs.documentationPath }}
      readmeFilepath: ${{ needs.agentic-lib.outputs.readmeFilepath }}
      missionFilepath: ${{ needs.agentic-lib.outputs.missionFilepath }}
      contributingFilepath: ${{ needs.agentic-lib.outputs.contributingFilepath }}
      dependenciesFilepath: ${{ needs.agentic-lib.outputs.dependenciesFilepath }}
      writeableFilepaths: ${{ needs.agentic-lib.outputs.writeableFilepaths }}
      model: ${{ vars.CHATGPT_API_MODEL || 'o4-mini' }}
      npmAuthOrganisation: ${{ vars.npmAuthOrganisation || '@xn-intenton-z2a' }}
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
    secrets:
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  #feature-to-issue:
  #  needs:
  #    - maintain-features
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #    checks: write
  #    issues: write
  #    id-token: write
  #    pages: write
  #  uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/agent-transformation-feature-to-issue.yml@6.4.7'
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #    CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}

  #ready-issue:
  #  needs:
  #    - feature-to-issue
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #    checks: write
  #    issues: write
  #    id-token: write
  #    pages: write
  #  uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/agent-transformation-issue-to-ready-issue.yml@6.4.7'
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #    CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}

  #issue-to-code:
  #  needs:
  #    - ready-issue
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #    checks: write
  #    issues: write
  #    id-token: write
  #    pages: write
  #  uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/agent-transformation-issue-to-code.yml@6.4.7'
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #    CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}

  #review-issue:
  #  needs:
  #    - issue-to-code
  #  permissions:
  #    contents: write
  #    issues: write
  #    id-token: write
  #    pages: write
  #  uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/agent-transformation-merged-issue-to-closed-issue.yml@6.4.7'
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #    CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
